package api

import (
	"net/http"
	"reflect"
	"strings"
)

// The OpenAPI document, generated by reflecting over the published route table
// and the response types the handlers actually serialize.
//
// Built at each request rather than generated into a file. A generated file is
// another copy that can be forgotten — this cannot disagree with the code,
// because it is the code, read at run time.
//
// Reflection needs two accommodations and no more, which is what the json and
// doc tags bought: embedded structs are inlined rather than nested, and
// json.RawMessage is arbitrary JSON rather than the byte string its underlying
// []byte would suggest. The one shape reflection cannot express is written by
// hand: annotateRequestSchema.

// schema is the subset of JSON Schema this needs.
type schema struct {
	Type        string             `json:"type,omitempty"`
	Format      string             `json:"format,omitempty"`
	Description string             `json:"description,omitempty"`
	Properties  map[string]*schema `json:"properties,omitempty"`
	Required    []string           `json:"required,omitempty"`
	Items       *schema            `json:"items,omitempty"`
	OneOf       []*schema          `json:"oneOf,omitempty"`
	Enum        []string           `json:"enum,omitempty"`
	// AdditionalProperties is true for an open map, and nil otherwise.
	AdditionalProperties any `json:"additionalProperties,omitempty"`
}

// schemaOf reflects a value into a schema.
func schemaOf(v any) *schema {
	if v == nil {
		return nil
	}
	return schemaOfType(reflect.TypeOf(v), map[reflect.Type]bool{})
}

func schemaOfType(t reflect.Type, seen map[reflect.Type]bool) *schema {
	// json.RawMessage is []byte with its own marshaller: the bytes are a JSON
	// document, not a base64 string. Checked before the slice unwrap below,
	// which would otherwise walk into uint8.
	if t.String() == "json.RawMessage" {
		return &schema{Description: "Arbitrary JSON."}
	}
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.String:
		return &schema{Type: "string"}
	case reflect.Bool:
		return &schema{Type: "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32:
		return &schema{Type: "integer"}
	case reflect.Int64:
		return &schema{Type: "integer", Format: "int64"}
	case reflect.Float32, reflect.Float64:
		return &schema{Type: "number"}
	case reflect.Interface:
		// No type to reflect. A route needing one supplies RequestSchema.
		return &schema{Description: "Any JSON value."}
	case reflect.Slice, reflect.Array:
		return &schema{Type: "array", Items: schemaOfType(t.Elem(), seen)}
	case reflect.Map:
		return &schema{Type: "object", AdditionalProperties: schemaOfType(t.Elem(), seen)}
	case reflect.Struct:
		// A cycle would recurse forever. Nothing published has one today, so
		// this is a guard rather than a feature: the schema degrades to an open
		// object rather than hanging the server.
		if seen[t] {
			return &schema{Type: "object"}
		}
		seen[t] = true
		defer delete(seen, t)

		out := &schema{Type: "object", Properties: map[string]*schema{}}
		collectFields(t, out, seen)
		if len(out.Required) == 0 {
			out.Required = nil
		}
		return out
	default:
		return &schema{}
	}
}

// collectFields walks a struct's fields into a schema, inlining embedded ones.
//
// Inlining is what makes the schema match the wire: an untagged embedded struct
// has its fields promoted by encoding/json, so a nested object here would
// describe a shape the server never sends.
func collectFields(t reflect.Type, out *schema, seen map[reflect.Type]bool) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue // unexported is never serialized
		}
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name, opts, _ := strings.Cut(tag, ",")
		if f.Anonymous && name == "" {
			ft := f.Type
			for ft.Kind() == reflect.Ptr {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				collectFields(ft, out, seen)
				continue
			}
		}
		if name == "" {
			// Untagged fields are a test failure, not a case to handle: see
			// TestPublishedTypesTagEveryExportedField. Falling back to the Go
			// name here would let one through quietly.
			name = f.Name
		}
		fs := schemaOfType(f.Type, seen)
		if doc := f.Tag.Get("doc"); doc != "" {
			fs.Description = doc
		}
		out.Properties[name] = fs
		// omitempty is how this codebase says "may be absent". Everything else
		// is always written, so it is required.
		if !strings.Contains(opts, "omitempty") {
			out.Required = append(out.Required, name)
		}
	}
}

// annotateRequestSchema is the one shape reflection cannot produce.
//
// Annotations is `any` on purpose: omitted means the snapshot's defaults, "all"
// means every field, and a list — as a comma string or an array — means those
// fields. That is a union, and a Go interface carries no trace of it.
func annotateRequestSchema() *schema {
	return &schema{
		Type: "object",
		Properties: map[string]*schema{
			"snapshot": {Type: "string", Description: "Annotate against this snapshot. " +
				"Mutually exclusive with sources."},
			"sources": {Type: "array", Items: &schema{Type: "string"},
				Description: "Annotate against these source ids. Requires build, and " +
					"becomes a generated snapshot so the run stays reproducible."},
			"build": {Type: "string", Description: "The genome assembly, required with " +
				"sources. Matched exactly: GRCh38 and hg38 are different builds."},
			"variants": {Type: "array", Items: &schema{Type: "string"},
				Description: "Variants as chrom:pos:ref:alt, e.g. chr12:25245350:C:T. " +
					"HGVS and rsIDs are not accepted."},
			"annotations": {
				Description: "Which fields to return. Omit for the snapshot's defaults.",
				OneOf: []*schema{
					{Type: "string", Description: "\"all\", or a comma-separated list."},
					{Type: "array", Items: &schema{Type: "string"},
						Description: "The field names to return."},
				},
			},
		},
		Required: []string{"variants"},
	}
}

// openAPI builds the document.
func (s *Server) openAPI() map[string]any {
	paths := map[string]any{}
	for _, rt := range s.publishedRoutes() {
		op := map[string]any{
			"operationId": rt.OpID,
			"summary":     rt.Summary,
			"tags":        []string{tagFor(rt.Path)},
		}
		if len(rt.Params) > 0 {
			ps := make([]map[string]any, 0, len(rt.Params))
			for _, p := range rt.Params {
				sch := &schema{Type: p.Type, Enum: p.Enum}
				ps = append(ps, map[string]any{
					"name": p.Name, "in": p.In, "required": p.Required,
					"description": p.Doc, "schema": sch,
				})
			}
			op["parameters"] = ps
		}
		if body := rt.RequestSchema; body != nil {
			op["requestBody"] = map[string]any{
				"required": true,
				"content":  map[string]any{"application/json": map[string]any{"schema": body}},
			}
		} else if rt.Request != nil {
			op["requestBody"] = map[string]any{
				"required": true,
				"content": map[string]any{
					"application/json": map[string]any{"schema": schemaOf(rt.Request)},
				},
			}
		}
		if rt.Method == "POST" && rt.Path == "/api/v1/annotate/vcf" {
			op["requestBody"] = map[string]any{
				"required": true,
				"content": map[string]any{
					"multipart/form-data": map[string]any{
						"schema": &schema{
							Type: "object",
							Properties: map[string]*schema{
								"vcf": {Type: "string", Format: "binary",
									Description: "The VCF file to annotate."},
								"snapshot": {Type: "string", Description: "Annotate against this snapshot."},
								"sources":  {Type: "string", Description: "Comma-separated source ids."},
								"build":    {Type: "string", Description: "The genome assembly, required with sources."},
								"annotations": {Type: "string",
									Description: "\"all\", or a comma-separated list of field names."},
							},
							Required: []string{"vcf"},
						},
					},
				},
			}
		}

		status := rt.Status
		if status == 0 {
			status = http.StatusOK
		}
		success := map[string]any{"description": "Success."}
		if rt.Response != nil {
			success["content"] = map[string]any{
				"application/json": map[string]any{"schema": schemaOf(rt.Response)},
			}
		} else if rt.Produces != "" {
			success["description"] = "The results, streamed in the requested format."
			success["content"] = map[string]any{rt.Produces: map[string]any{}}
		}
		errSchema := map[string]any{
			"application/json": map[string]any{"schema": schemaOf(ErrorResponse{})},
		}
		op["responses"] = map[string]any{
			itoa(status): success,
			"401":        map[string]any{"description": "No credential, or one that is not valid.", "content": errSchema},
			"404":        map[string]any{"description": "No such thing, or not visible to this caller.", "content": errSchema},
		}

		entry, ok := paths[rt.Path].(map[string]any)
		if !ok {
			entry = map[string]any{}
			paths[rt.Path] = entry
		}
		entry[strings.ToLower(rt.Method)] = op
	}

	return map[string]any{
		"openapi": "3.1.0",
		"info": map[string]any{
			"title":   "VariantHub API",
			"version": s.cfg.Version,
			"description": "Annotate variants against versioned, pinned bundles of " +
				"reference sources.\n\n" +
				"Authenticate with a personal API token: `Authorization: Bearer cgl_vh_...`. " +
				"Tokens are issued in the web application and carry their owner's " +
				"permissions, read fresh at each request.\n\n" +
				"This is the whole published API. Account management and administration " +
				"are part of the web application rather than of this contract, and are " +
				"not reachable with a token.",
		},
		"servers": []map[string]any{{"url": "/"}},
		"components": map[string]any{
			"securitySchemes": map[string]any{
				"bearer": map[string]any{
					"type": "http", "scheme": "bearer",
					"description": "A personal API token, issued in the web application.",
				},
			},
		},
		"security": []map[string]any{{"bearer": []string{}}},
		"paths":    paths,
	}
}

// tagFor groups operations in the document by their first path segment.
func tagFor(path string) string {
	p := strings.TrimPrefix(path, "/api/v1/")
	if i := strings.Index(p, "/"); i > 0 {
		p = p[:i]
	}
	if p == "" {
		return "general"
	}
	return p
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b [8]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	return string(b[i:])
}

// handleOpenAPI serves the document.
func (s *Server) handleOpenAPI(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, s.openAPI())
}
